### List Products
# @name ProductList
GET http://localhost:7000/api/v1/products HTTP/1.1


### Save Product
# @name Saveproduct
POST http://localhost:7000/api/v1/products HTTP/1.1
Content-Type: application/json

{
    "name":"Potatoes sweet",
    "price":"2500.00",
    "productCode":"PotShgwe89887123",
    "productCategory": "FRUIT",
    "imageUrl": "https://cdn.mos.cms.futurecdn.net/iC7HBvohbJqExqvbKcV3pP-1200-80.jpg",
    "quantity": 1600
}


### Get Product
# @name GetProductById
GET http://localhost:7000/api/v1/products/3 HTTP/1.1


### Place Order
# @name placeorder
POST http://localhost:7000/api/v1/orders/placeOrder HTTP/1.1
Content-Type: application/json

{
   "orderItems":[
        {
            "productCode":"ereh857453",
            "quantity":10
        }
      
       
   ]
}

### List Orders
# @name OrderList
GET http://localhost:7000/api/v1/orders HTTP/1.1


### Save Inventory
# @name Saveinventory
POST http://localhost:7000/api/v1/inventory/createInventory HTTP/1.1
Content-Type: application/json

{
    "productCode":"eh857453",
    "quantity":500
    
}