server:
  port: 6001
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: test1
    password: test1
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

