server:
  port: 6000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: test1
    password: test1
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka