server:
  port: 6000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productdb
    username: test1
    password: test1
  application:
    name: product-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


